language: node_js

branches:
  only:
    - master

before_script: bash ./bin/prepare.sh

script:
    - ls -al

after_success: bash ./bin/deploy.sh

env:
  global:
  - secure: "F/Q1qvPSJQDXM2uBNWGCePFAewtOJAhGIn+Ef665YutuhObyE3+LN8/UOyHb37rYdtseLR1ZOzm1Tuhw2s/6hwl5qrOf/uA++bR4Fy456TWzeJ3ef/x2msdJYkWKCDxD4lKxUvpeemj4mosM61MyzLHNNMnheHFV8nnEro37ntwMxPCDFG5Bn+lOYb6tttN84vK+UU+ld1rxNxrP+TdlygFwdoheZV7T7z6DTllxVLNlBeWOM9XgIePKOYxC269knXIEIkqapUPnjUmmuwm5e1w/1WR4c8ggldW0vd0+rOR3/zZzOKhzgzXt/9Sk0L8zoKTQ3l6Im8k/etU/Sa36C14bcXJQPFRDBx/kl/nh57OBG2vN5fNyx+Vl6IL7nmEijHSnSKamZ3QR4w4q640Ukd+4zIk6nTi6Jc7dygdTFLu4OKD7tGs5mJo+YTZUMxvSAblAoMBSm9zfzmvDhYR1jIVJkVc46gYL8jKBCaFv38S5Ouvf9zcmmbhhEzqfSMninrM1+Eei4Wi89p/0laVM2WXAausPTcC843XbL4g0sc738NiS8PLhh54GxbEPmqxReaczI3Ljua1Bo58BzVEQKu1BIdQAJIBZTjTD/G+X9rviS65p++msXKm44YCZMskknfEkENP9rDr6P2fDxQZyoEyxsz1guGkfDSpch84RmEk="
